# Generated by Django 5.2.5 on 2025-08-20 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
